FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .

RUN python3 -m venv /opt/venv

RUN /opt/venv/bin/pip install --upgrade pip && \
    /opt/venv/bin/pip install -r requirements.txt

COPY . .

CMD ["/opt/venv/bin/python3", "main.py"]