FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .

RUN python3 -m venv /app/venv

RUN /app/venv/bin/pip install --upgrade pip && \
    /app/venv/bin/pip install -r requirements.txt

COPY . .

CMD ["/app/venv/bin/python", "main.py"]